/*
 * Aclass allows to add single message
 */
package nbm;
import java.awt.Color;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

/**
 * @author Jurek
 */
public class AddMessage extends javax.swing.JPanel {

    private final Message message;
    
    // constructor
    public AddMessage(Message mess) {
        initComponents();
        message = mess;
    }

  // adds text to text pane when processing message
  private void appendToPane(JTextPane textPane, String msg, Color color)
    {
        StyleContext styleContext = StyleContext.getDefaultStyleContext();
        AttributeSet attribSet = styleContext.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, color);
        attribSet = styleContext.addAttribute(attribSet, StyleConstants.FontFamily, "Arial");
        attribSet = styleContext.addAttribute(attribSet, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);
        int length = textPane.getDocument().getLength();
        textPane.setCaretPosition(length);
        textPane.setCharacterAttributes(attribSet, false);
        textPane.replaceSelection(msg);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeaderText = new javax.swing.JLabel();
        textFieldHeader = new javax.swing.JTextField();
        labelBodyText = new javax.swing.JLabel();
        scrollPaneBody = new javax.swing.JScrollPane();
        textAreaBody = new javax.swing.JTextArea();
        buttonAdd = new javax.swing.JButton();
        scrollPaneStatus = new javax.swing.JScrollPane();
        textPaneStatus = new javax.swing.JTextPane();
        scrollPaneSIR = new javax.swing.JScrollPane();
        textAreaSIR = new javax.swing.JTextArea();
        scrollPaneMentions = new javax.swing.JScrollPane();
        textAreaMentions = new javax.swing.JTextArea();
        scrollPaneTrending = new javax.swing.JScrollPane();
        textAreaTrending = new javax.swing.JTextArea();
        labelStatus = new javax.swing.JLabel();
        labelSIR = new javax.swing.JLabel();
        labelMentions = new javax.swing.JLabel();
        labelTrending = new javax.swing.JLabel();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(760, 560));
        setMinimumSize(new java.awt.Dimension(760, 560));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(760, 560));

        labelHeaderText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelHeaderText.setText(" Header:");

        textFieldHeader.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelBodyText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelBodyText.setText(" Body:");

        textAreaBody.setColumns(20);
        textAreaBody.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaBody.setLineWrap(true);
        textAreaBody.setRows(4);
        scrollPaneBody.setViewportView(textAreaBody);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        textPaneStatus.setEditable(false);
        textPaneStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textPaneStatus.setPreferredSize(new java.awt.Dimension(4, 20));
        scrollPaneStatus.setViewportView(textPaneStatus);

        textAreaSIR.setEditable(false);
        textAreaSIR.setColumns(20);
        textAreaSIR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaSIR.setRows(3);
        scrollPaneSIR.setViewportView(textAreaSIR);

        textAreaMentions.setEditable(false);
        textAreaMentions.setColumns(16);
        textAreaMentions.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaMentions.setRows(3);
        textAreaMentions.setTabSize(4);
        scrollPaneMentions.setViewportView(textAreaMentions);

        textAreaTrending.setEditable(false);
        textAreaTrending.setColumns(16);
        textAreaTrending.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textAreaTrending.setRows(3);
        textAreaTrending.setTabSize(4);
        scrollPaneTrending.setViewportView(textAreaTrending);

        labelStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelStatus.setText(" Status:");

        labelSIR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelSIR.setText(" SIR List:");

        labelMentions.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelMentions.setText("Mention List:");

        labelTrending.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTrending.setText(" Trending List:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneStatus)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelBodyText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldHeader)
                                .addComponent(labelHeaderText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addComponent(buttonAdd)
                            .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSIR, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneSIR, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMentions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollPaneMentions, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTrending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollPaneTrending, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addComponent(scrollPaneBody))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeaderText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBodyText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSIR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMentions)
                        .addComponent(labelTrending)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneSIR)
                    .addComponent(scrollPaneMentions)
                    .addComponent(scrollPaneTrending, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
          
            textAreaMentions.setText("");                             // clears trending list textarea
            textAreaTrending.setText("");                             // clears mentions list textarea
            textAreaSIR.setText("");                                  // clears SIR list textarea
            textPaneStatus.setText("");                               // clears status textPane
            textPaneStatus.setEditable(true);                         // allows edit status textPane
            // adds message and gets status messages
            String status[] = message.addMessage(textFieldHeader.getText(), textAreaBody.getText());
            boolean noerror = true;
            // set status messages
            for(int i=0; i<status.length; i++)
            {
            if(!status[i].equals(""))
            {
                if(!status[i].startsWith("Error"))
                {
                    appendToPane(textPaneStatus, status[i], Color.BLACK);
                }
                else
                {
                    noerror = false;
                    appendToPane(textPaneStatus, status[i], Color.RED); 
                }
            }    
            }

            if(noerror)     // if message was successfully added then display 
            {
            textAreaMentions.setText(message.getTrending());            // set trending list textarea
            textAreaTrending.setText(message.getMentions());            // set mentions list textarea
            textAreaSIR.setText(message.getSIR());                      // set sir list textarea
            textFieldHeader.setText("");                                // sets header as empty
            textAreaBody.setText("");                                   // sets body as empty
            }
            textPaneStatus.setEditable(false);                          // removes editability from status textPane
            
    }//GEN-LAST:event_buttonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JLabel labelBodyText;
    private javax.swing.JLabel labelHeaderText;
    private javax.swing.JLabel labelMentions;
    private javax.swing.JLabel labelSIR;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTrending;
    private javax.swing.JScrollPane scrollPaneBody;
    private javax.swing.JScrollPane scrollPaneMentions;
    private javax.swing.JScrollPane scrollPaneSIR;
    private javax.swing.JScrollPane scrollPaneStatus;
    private javax.swing.JScrollPane scrollPaneTrending;
    private javax.swing.JTextArea textAreaBody;
    private javax.swing.JTextArea textAreaMentions;
    private javax.swing.JTextArea textAreaSIR;
    private javax.swing.JTextArea textAreaTrending;
    private javax.swing.JTextField textFieldHeader;
    private javax.swing.JTextPane textPaneStatus;
    // End of variables declaration//GEN-END:variables
}
