/*
 * Main class responsible for running the whole program
 */
package nbm;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 * 
 * @author Jurek
 */
public class NBM extends javax.swing.JDialog {

    private final Message message;          // utility object
    private final AddMessage addMessage;    // addMassage object
    private final OpenFile openFile;        // openFile object
    private final About about;              // about object
    
    /**
     * Creates new form NBM
     * @param parent
     * @param modal
     */
    
    // constructor
    public NBM(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        // if file "messages.json" does not exist create it
        File messFile = new File("messages.json");
        if(!messFile.exists())
        {
            try { messFile.createNewFile();} 
            catch (IOException ex) { Logger.getLogger(NBM.class.getName()).log(Level.SEVERE, null, ex);}
        }
        
        // if file "trending.txt" does not exist create it
        File trendinglist = new File("trending.txt");
        if(!trendinglist.exists())
        {
            try { trendinglist.createNewFile();} 
            catch (IOException ex) { Logger.getLogger(NBM.class.getName()).log(Level.SEVERE, null, ex);}
        }
        
        // if file "mentions.txt" does not exist create it
        File mentions = new File("mentions.txt");
        if(!mentions.exists())
        {
            try { mentions.createNewFile();} 
            catch (IOException ex) { Logger.getLogger(NBM.class.getName()).log(Level.SEVERE, null, ex);}
        }
        
        // if file "sir.txt" does not exist create it
        File sir = new File("sir.txt");
        if(!sir.exists())
        {
            try { sir.createNewFile();} 
            catch (IOException ex) { Logger.getLogger(NBM.class.getName()).log(Level.SEVERE, null, ex);}
        }
        
        message = new Message("textwords.csv", "messages.json", "trending.txt", "mentions.txt", "sir.txt"); // initialize utility object
        addMessage = new AddMessage(message);       // initialize addMessage
        openFile = new OpenFile(message);           // initialize openFile
        about = new About();                        // initialize about
        switchPanel(addMessage);                    // sets addMessage panel as current panel   
    }
 
    // method allows to switch between panels
    private void switchPanel(JPanel panel)
    {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mItemAddMessage = new javax.swing.JMenuItem();
        mItemOpenFile = new javax.swing.JMenuItem();
        mItemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        mItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Napier Bank Messages");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 640));
        setMinimumSize(new java.awt.Dimension(800, 640));
        setPreferredSize(new java.awt.Dimension(800, 640));
        setResizable(false);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        menuFile.setText("File");

        mItemAddMessage.setText("Add Message");
        mItemAddMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAddMessageActionPerformed(evt);
            }
        });
        menuFile.add(mItemAddMessage);

        mItemOpenFile.setText("Open File");
        mItemOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemOpenFileActionPerformed(evt);
            }
        });
        menuFile.add(mItemOpenFile);

        mItemExit.setText("Exit");
        mItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemExitActionPerformed(evt);
            }
        });
        menuFile.add(mItemExit);

        menuBar.add(menuFile);

        menuHelp.setText("Help");

        mItemAbout.setText("About");
        mItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(mItemAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemAddMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAddMessageActionPerformed
        switchPanel(addMessage);
    }//GEN-LAST:event_mItemAddMessageActionPerformed

    private void mItemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemOpenFileActionPerformed
       switchPanel(openFile);
    }//GEN-LAST:event_mItemOpenFileActionPerformed
    // exit program
    private void mItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mItemExitActionPerformed

    private void mItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAboutActionPerformed
        switchPanel(about);
    }//GEN-LAST:event_mItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            NBM dialog = new NBM(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem mItemAbout;
    private javax.swing.JMenuItem mItemAddMessage;
    private javax.swing.JMenuItem mItemExit;
    private javax.swing.JMenuItem mItemOpenFile;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    // End of variables declaration//GEN-END:variables
}
